
version: '3'

services:
  flask-app-server:
    environment:
      env_file: "./src/.env"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/usr/src/app/src:Z
