"""empty message

Revision ID: de2a042eb9b9
Revises: 
Create Date: 2023-02-21 01:19:26.661073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2a042eb9b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('avg_max_temp', sa.Float(), nullable=True),
    sa.Column('avg_min_temp', sa.Float(), nullable=True),
    sa.Column('total_precipitation', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.create_table('weather_data',
    sa.Column('station_code', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('max_temp', sa.Integer(), nullable=True),
    sa.Column('min_temp', sa.Integer(), nullable=True),
    sa.Column('precipitation', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_code', 'date', name='station_date_uc')
    )
    op.create_table('yield_data',
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('crop', sa.String(), nullable=True),
    sa.Column('k_metric_tons', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yield_data')
    op.drop_table('weather_data')
    op.drop_table('analyses')
    # ### end Alembic commands ###
